version: '3.0'  # 使用 Docker Compose 的版本 3.0，適合大部分部署場景

services:
  # MySQL 服務
  mysql:
    image: mysql:8.0
    # 設定 mysql 使用原生認證的密碼 hash
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: user
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: mydb
    volumes:
      - mysql:/var/lib/mysql
    # 以下是 Docker Swarm 模式的設定
    deploy:
      mode: replicated              # 使用 replicated 模式，非 global
      replicas: 1                   # 執行 1 個副本
      placement:
        # 只允許在 manager 節點部署此服務（可改為 node label）
        constraints: [node.role == manager]
        # constraints: [node.labels.mysql == true]
    networks:
      - jobmarket-swarm-network

  # phpMyAdmin (可選)
  phpmyadmin:
    # image: phpmyadmin/phpmyadmin:5.1.0
    image: arm64v8/phpmyadmin
    # 這個在新版 Docker Compose 中不需要
    # links: 
    #     - mysql:db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: mydb
    depends_on:
      - mysql
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
        # constraints: [node.labels.mysql == true]
    networks:
      - jobmarket-swarm-network

networks:
  jobmarket-swarm-network:
    # 加入已經存在的網路
    external: true

volumes:
  mysql:
