version: '3.0'  # 使用 Docker Compose 的版本 3.0，適合大部分部署場景

services:
  # RabbitMQ 服務
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=worker
      - RABBITMQ_DEFAULT_PASS=worker
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    # Docker Swarm 模式的設定
    deploy:
      mode: replicated                      # 啟用 replicated 模式
      replicas: 1                           # 啟動一個副本（通常不會是 global）
      placement:
        constraints: [node.role == manager] # 限定只能部署到 manager 節點（可改為 node label）
        # constraints: [node.labels.rabbitmq == true]
    networks:
      - jobmarket-swarm-network

  # Flower (Celery 監控)
  flower:
    # NOTE: Windows 環境下使用這個
    # image: mher/flower:0.9.5
    # command: ["flower", "--broker=amqp://worker:worker@rabbitmq", "--port=5555"]
    image: mher/flower:1.2.0
    command: ["celery", "--broker=amqp://worker:worker@rabbitmq", "flower", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
    # Swarm 部署設定
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
        # constraints: [node.labels.rabbitmq == true]
    networks:
      - jobmarket-swarm-network

networks:
  jobmarket-swarm-network:
    # 加入已經存在的網路
    external: true

volumes:
  rabbitmq_data: